version: '2'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tax_calculator
      MYSQL_ROOT_PASSWORD: alwayshandsomebro
    expose:
      - '3306'
  web:
    build: ./
    volumes:
      -  ./:/tax-calculator
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db